---

version: "3.9"

services:
    node1:
        container_name: gandalf_1
        image: gandalf:latest
        restart: always
        environment:
            - RUST_LOG=info
        volumes:
            - ./gandalf_1.conf:/etc/gandalf.conf
        networks:
            vpcbr:
                ipv4_address: 10.5.0.2
        depends_on:
            - kvs1

    node2:
        container_name: gandalf_2
        image: gandalf:latest
        restart: always
        environment:
            - RUST_LOG=info
        volumes:
            - ./gandalf_2.conf:/etc/gandalf.conf
        networks:
            vpcbr:
                ipv4_address: 10.5.0.3
        depends_on:
            - kvs2

    node3:
        container_name: gandalf_3
        image: gandalf:latest
        restart: always
        environment:
            - RUST_LOG=info
        volumes:
            - ./gandalf_3.conf:/etc/gandalf.conf
        networks:
            vpcbr:
                ipv4_address: 10.5.0.4
        depends_on:
            - kvs3

    kvs1:
        container_name: kvs_1
        image: gandalf-kvs:latest
        restart: always
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5

    kvs2:
        container_name: kvs_2
        image: gandalf-kvs:latest
        restart: always
        networks:
            vpcbr:
                ipv4_address: 10.5.0.6

    kvs3:
        container_name: kvs_3
        image: gandalf-kvs:latest
        restart: always
        networks:
            vpcbr:
                ipv4_address: 10.5.0.7


networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/24

